### PR TITLE
test-req install

### PR DESCRIPTION
**Pull request by Alexei-Kornienko**

### CODE REVIEW

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/1/

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/2/

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/3/

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by Alexei-Kornienko** [comment]
hawthorn run python

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/4/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/2/'>http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/</a>

**Comment by Alexei-Kornienko** [comment]
hawthorn run python

**Comment by Alexei-Kornienko** [comment]
hawthorn run python

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/4/'>http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/4/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/33/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/33/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/25/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/25/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/20/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/20/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/19/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/19/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/21/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/21/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/22/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/22/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/23/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/23/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/24/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/24/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/26/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/26/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/27/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/27/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/28/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/28/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/29/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/29/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/30/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/30/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/31/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/31/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/32/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/32/</a>

**Pull request closed without merging**
