### PR TITLE
Test pr jobs.

### PR DESCRIPTION
**Pull request by svic**

### CODE REVIEW

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://localhost:8080/sample/job/hawthorn-python-unittests-pr/1/'>http://localhost:8080/sample/job/hawthorn-python-unittests-pr/1/</a>

**Comment by svic** [comment]
hawthorn run all

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
hawthorn run python

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://localhost:8080/sample/job/hawthorn-python-unittests-pr/2/'>http://localhost:8080/sample/job/hawthorn-python-unittests-pr/2/</a>

**Comment by svic** [comment]
hawthorn run a11y

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/2/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/2/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/1/

**Comment by Alexei-Kornienko** [comment]
hawthorn run a11y

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-quality-flow-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-quality-flow-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/16/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/16/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/17/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/17/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-lettuce-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-lettuce-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/29/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/29/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/32/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/32/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/18/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/18/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/19/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/19/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/23/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/23/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/25/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/25/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/31/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/31/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/34/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/34/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/40/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/40/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-bok-choy-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-bok-choy-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/20/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/20/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/21/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/21/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/22/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/22/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/24/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/24/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/26/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/26/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/27/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/27/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/28/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/28/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/30/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/30/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/33/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/33/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/35/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/35/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/36/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/36/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/37/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/37/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/38/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/38/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/39/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/39/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/41/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/41/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/42/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/42/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/43/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/43/</a>

**Comment by Alexei-Kornienko** [comment]
hawthorn run a11y

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/2/

**Comment by Alexei-Kornienko** [comment]
hawthorn run python

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/2/'>http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/45/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/45/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/46/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/46/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/44/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/44/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/47/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/47/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/48/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/48/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/49/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/49/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/50/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/50/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/51/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/51/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/52/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/52/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/53/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/53/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/54/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/54/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/55/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/55/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/56/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/56/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/57/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/57/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/58/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/58/</a>

**Comment by Alexei-Kornienko** [comment]
jenkins run js

**Comment by Alexei-Kornienko** [comment]
jenkins run python

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins-ci.raccoongang.com/job/hawthorn-js-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/16/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/16/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/18/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/18/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/20/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/20/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/22/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/22/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/24/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/24/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/26/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/26/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/27/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/27/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-bok-choy-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-bok-choy-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/17/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/17/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/19/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/19/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/21/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/21/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/23/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/23/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/25/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/25/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/31/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/31/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/28/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/28/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/29/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/29/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/30/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/30/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/32/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/32/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/33/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/33/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/34/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/34/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/35/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/35/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/36/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/36/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/37/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/37/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-lettuce-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-lettuce-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/38/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/38/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/39/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/39/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-quality-flow-pr/1/'>http://jenkins-ci.raccoongang.com/job/hawthorn-quality-flow-pr/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/40/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/40/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/41/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/41/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/43/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/43/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/42/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/42/</a>

**Comment by Alexei-Kornienko** [comment]
jenkins run all

**Comment by Alexei-Kornienko** [comment]
jenkins run python

**Pull request closed without merging**
